import { useQuery } from '@tanstack/react-query';
import { roleAtLeast, type ProjectDto, type ProjectRole } from '@grids/schema';
import {
  Activity,
  Ambulance,
  Baby,
  BedDouble,
  Beef,
  Bike,
  Box,
  Boxes,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Church,
  Circle,
  ClipboardList,
  CloudRain,
  Compass,
  Database,
  Droplets,
  Factory,
  FileText,
  Fish,
  Flag,
  Folder,
  Fuel,
  Globe,
  GraduationCap,
  Hammer,
  HeartPulse,
  Hexagon,
  Hospital,
  House,
  Landmark,
  Leaf,
  Map as MapIcon,
  MapPin,
  Mountain,
  Package,
  Phone,
  Pill,
  Plane,
  Plug,
  RadioTower,
  Route,
  School,
  Server,
  Shield,
  Ship,
  Sprout,
  Square,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Target,
  Tent,
  Thermometer,
  Tractor,
  TreePine,
  Triangle,
  Truck,
  UserRound,
  Users,
  Warehouse,
  Waves,
  Wheat,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { createContext, useContext } from 'react';
import { api } from '../../api';

/** Icons projects and entity types can use (by name). */
export const ICONS: Record<string, LucideIcon> = {
  'activity': Activity,
  'folder': Folder,
  'plane': Plane,
  'hospital': Hospital,
  'heart-pulse': HeartPulse,
  'users': Users,
  'user-round': UserRound,
  'building-2': Building2,
  'droplets': Droplets,
  'map': MapIcon,
  'map-pin': MapPin,
  'sprout': Sprout,
  'truck': Truck,
  'box': Box,
  'flag': Flag,
  'school': School,
  'graduation-cap': GraduationCap,
  'home': House,
  'store': Store,
  'factory': Factory,
  'warehouse': Warehouse,
  'landmark': Landmark,
  'church': Church,
  'tent': Tent,
  'tree-pine': TreePine,
  'leaf': Leaf,
  'wheat': Wheat,
  'fish': Fish,
  'beef': Beef,
  'tractor': Tractor,
  'car': Car,
  'bus': Bus,
  'ship': Ship,
  'bike': Bike,
  'fuel': Fuel,
  'zap': Zap,
  'plug': Plug,
  'sun': Sun,
  'cloud-rain': CloudRain,
  'thermometer': Thermometer,
  'waves': Waves,
  'mountain': Mountain,
  'syringe': Syringe,
  'pill': Pill,
  'stethoscope': Stethoscope,
  'baby': Baby,
  'bed': BedDouble,
  'ambulance': Ambulance,
  'shield': Shield,
  'briefcase': Briefcase,
  'wrench': Wrench,
  'hammer': Hammer,
  'package': Package,
  'boxes': Boxes,
  'clipboard': ClipboardList,
  'file-text': FileText,
  'database': Database,
  'server': Server,
  'wifi': Wifi,
  'radio-tower': RadioTower,
  'phone': Phone,
  'camera': Camera,
  'globe': Globe,
  'compass': Compass,
  'route': Route,
  'target': Target,
  'star': Star,
  'circle': Circle,
  'square': Square,
  'triangle': Triangle,
  'hexagon': Hexagon,
};
export const iconOf = (name: string) => ICONS[name] ?? Box;

interface ProjectCtx {
  project: ProjectDto;
  tenantId: string;
  /** /o/:tenantId/p/:projectKey */
  base: string;
  can: (role: ProjectRole) => boolean;
}
const Ctx = createContext<ProjectCtx | null>(null);
export const ProjectProvider = Ctx.Provider;
export function useProject() {
  const c = useContext(Ctx);
  if (!c) throw new Error('useProject outside a project');
  return c;
}
export const projectCtx = (project: ProjectDto, tenantId: string): ProjectCtx => ({
  project,
  tenantId,
  base: `/o/${tenantId}/p/${project.key}`,
  can: (role) => roleAtLeast(project.myRole, role),
});

/** Data elements by key → name (legends, labels). */
export function useElementNames() {
  const { tenantId, project } = useProject();
  const q = useQuery({ queryKey: ['elements', tenantId, project.key], queryFn: () => api.elements(tenantId, project.key) });
  return Object.fromEntries((q.data ?? []).map((e) => [e.key, e.name]));
}
